### ISSUE TITLE
PostCSS fails with purgecss-from-js enabled

### ISSUE THREAD

**Issue by JVanloofsvelt** [FullHuman/purgecss-from-js#7]
The following error is raised:
```
Error: Error building site: POSTCSS: failed to transform "css/github.min.css" (text/css): TypeError: t is not a function
    at b (C:\Users\meow\project\node_modules\purgecss\lib\purgecss.js:1:3593)
    at C.extractSelectorsFromFiles (C:\Users\meow\project\node_modules\purgecss\lib\purgecss.js:1:5787)
```

I have only one fairly small js file for purgecss to analyze, so perhaps the cause could be found easily. Let me know if you care to have a look at it.

**Comment by ElectronicRU** [comment]
To add some context, `require('postcss-from-js')` resolves into `require('postcss-from-js/dist/main.js')` which results in `{}`. Maybe the `package.json` file needs a `module` declaration?
